services:
  marreta:
    image: ghcr.io/manualdousuario/marreta:latest
    container_name: marreta
    restart: unless-stopped
    environment:
      - SITE_URL=https://ram.rabalski.eu
      - SITE_NAME=Marreta
      - SITE_DESCRIPTION=Clean reading, fewer blockers
      - SELENIUM_HOST=selenium-hub:4444
      - DNS_SERVERS=1.1.1.1,8.8.8.8
      - LOG_LEVEL=WARNING
      - LANGUAGE=en
    labels:
      - "glance.name=Marreta"
      - "glance.icon=sh:hammer"
      - "glance.url=https://ram.rabalski.eu"
      - "glance.description=Paywall Bypass"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
