services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    # ---- Option A (HTTPS upstream to 9443) ----
    # command: []
    # ---- Option B (HTTP upstream to 9000) ----
    command: ["--http-enabled"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - caddy_net
    ports:
      - "9000:9000"
    

networks:
  caddy_net:
    external: true

volumes:
  portainer_data:
