services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    volumes:
      - /opt/glance/glance.yml:/app/glance.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "glance.name=Glance"
      - "glance.icon=sh:layout-dashboard"
      - "glance.url=https://deck.rabalski.eu"
      - "glance.description=Dashboard"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
