services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    environment:
      - LAT=${LAT}
      - LON=${LON}
      - ADGUARD_USERNAME=${ADGUARD_USERNAME}
    volumes:
      - /opt/glance/assets:/app/assets:ro
      - /opt/glance/config:/app/config:rw
      - /opt/glance/secrets:/run/secrets:ro
      - /etc/localtime:/etc/localtime:ro
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "glance.name=Glance"
      - "glance.icon=sh:layout-dashboard"
      - "glance.url=https://deck.rabalski.eu"
      - "glance.description=Dashboard"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
