services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_184bf3194b53ef11b8be2ce0174bec31-if00-port0:/dev/ttyUSB0
    volumes:
      - /mnt/nvme/services/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev:ro
    ports:
      - "8123:8123"  # Expose port for narsis deployment
    labels:
      - "glance.name=Home Assistant"
      - "glance.icon=si:homeassistant"
      - "glance.url=https://dom.rabalski.eu"
      - "glance.description=Smart Home"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
