services:
  dumbpad:
    image: dumbwareio/dumbpad:latest
    container_name: dumbpad
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /mnt/nvme/services/dumbpad/data:/app/data
    labels:
      - "glance.name=Dumbpad"
      - "glance.icon=sh:notepad-text"
      - "glance.url=https://pad.rabalski.eu"
      - "glance.description=Note-taking"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
