version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=Europe/Warsaw
      - N8N_HOST=n8n.rabalski.eu
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=https://n8n.rabalski.eu
      - WEBHOOK_URL=https://n8n.rabalski.eu
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=1
      - N8N_RUNNERS_ENABLED=true
    labels:
      - "glance.name=n8n"
      - "glance.icon=sh:n8n-light"
      - "glance.url=n8n.rabalski.eu"
    volumes:
      - /opt/n8n/data:/home/node/.n8n
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
