- labels:
    job: http
  targets:
    - https://cloud.rabalski.eu
    - https://portainer.rabalski.eu
    - https://search.rabalski.eu
#    - https://21376942.rabalski.eu
    - https://sink.rabalski.eu
    - https://kicia.rabalski.eu
    - https://watch.rabalski.eu
    - https://deck.rabalski.eu
    - https://ram.rabalski.eu
    - https://pad.rabalski.eu
    - https://speedtest.rabalski.eu
    - https://aio-setup.rabalski.eu
    - https://dom.rabalski.eu
    - https://n8n.rabalski.eu
    - https://grafana.rabalski.eu
    - https://prometheus.rabalski.eu
