- labels:
    job: icmp
  targets:
    # LAN devices
    - 192.168.1.1       # home router
    - 192.168.1.10      # clockworkcity (LAN)
    - 192.168.1.2       # MikroTik
    # - 192.168.1.200     # Epson (uncomment if always online)
