services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=https://search.rabalski.eu/
      - SEARXNG_SECRET=${SEARXNG_SECRET:-}
    volumes:
      - /home/sothasil/searxng/searxng:/etc/searxng:rw
    labels:
      - "glance.name=SearXNG"
      - "glance.icon=si:searxng"
      - "glance.url=https://search.rabalski.eu"
      - "glance.description=Metasearch Engine"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
