networks:
  caddy_net:
    external: true

services:
  ipmi-exporter:
    image: prometheuscommunity/ipmi-exporter:v1.8.0
    container_name: ipmi-exporter
    restart: unless-stopped
    ports:
      - "9290:9290"
    networks:
      - caddy_net
    labels:
      glance.name: "IPMI Exporter"
      glance.icon: "mdi:chip"
