services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - BASE_URL=https://watch.rabalski.eu
    ports:
      - "5000:5000"
    volumes:
      - /mnt/nvme/services/changedetection/data:/datastore
    labels:
      - "glance.name=Changedetection"
      - "glance.icon=sh:eye"
      - "glance.url=https://watch.rabalski.eu"
      - "glance.description=Website Monitoring"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
