networks:
  caddy_net:
    external: true

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: ghcr.io/caddy-dns/cloudflare:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
      CLOUDFLARE_API_TOKEN: ${CF_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "8443:443/tcp"
      - "8443:443/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
