global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers: []

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: blackbox_icmp
    metrics_path: /probe
    scrape_interval: 15s
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/icmp_targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: blackbox_http
    metrics_path: /probe
    scrape_interval: 30s
    params:
      module: [http_success]
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/http_targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: blackbox_tcp
    metrics_path: /probe
    scrape_interval: 30s
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/tcp_targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
